 
include: package:flutter_lints/flutter.yaml

linter:
   
  rules:
    # Add or remove rules as needed
    prefer_const_constructors: true
    avoid_print: true
    annotate_overrides: true
    prefer_final_locals: true